// ── Stablecoin Dashboard Data ──────────────────────────────────────────────
// Last updated: March 2026

const ISSUERS = [
  {
    id: "tether",
    name: "Tether",
    shortName: "USDT",
    logoText: "₮",
    color: "#26A17B",
    type: "Centralized / Fiat-backed",
    founded: "2014",
    headquarters: "British Virgin Islands",
    regulatoryStatus: "Regulated in El Salvador",
    marketCap: "$143B",
    marketShare: 63.6,
    website: "https://tether.to",
    description:
      "Tether is the world's largest stablecoin issuer by market cap. Each USDT is backed 1:1 by reserves held in cash, cash equivalents, and short-term US Treasury bills. Tether operates across more blockchains than any other stablecoin issuer.",
    tags: ["Fiat-backed", "USD-pegged", "Largest by market cap"],
    stablecoins: [
      {
        ticker: "USDT",
        name: "Tether USD",
        peg: "USD",
        status: "active",
        marketCap: "$143B",
        backing: "Cash & T-bills (100%+)",
        chains: ["Ethereum", "Tron", "Solana", "BNB Chain", "Polygon", "Avalanche", "Arbitrum", "Optimism", "TON", "Aptos", "Sui", "Celo"],
        launched: "2014",
        notes: "World's largest stablecoin. USDT on Tron is the most transferred stablecoin by volume.",
      },
      {
        ticker: "XAUT",
        name: "Tether Gold",
        peg: "XAU (Gold)",
        status: "active",
        marketCap: "$780M",
        backing: "Physical gold",
        chains: ["Ethereum", "Tron"],
        launched: "2020",
        notes: "Each XAUT token represents one troy fine ounce of gold stored in Swiss vaults.",
      },
      {
        ticker: "EURT",
        name: "Tether EUR",
        peg: "EUR",
        status: "active",
        marketCap: "$38M",
        backing: "Cash & equivalents",
        chains: ["Ethereum", "Tron", "Algorand"],
        launched: "2016",
        notes: "Euro-pegged stablecoin with relatively low market cap compared to USDT.",
      },
      {
        ticker: "MXNT",
        name: "Tether MXN",
        peg: "MXN",
        status: "active",
        marketCap: "$2M",
        backing: "Cash & equivalents",
        chains: ["Ethereum", "Tron", "Polygon"],
        launched: "2022",
        notes: "Mexican Peso-pegged stablecoin targeting Latin American markets.",
      },
      {
        ticker: "GBPT",
        name: "Tether GBP",
        peg: "GBP",
        status: "active",
        marketCap: "$1M",
        backing: "Cash & equivalents",
        chains: ["Ethereum"],
        launched: "2023",
        notes: "British Pound-pegged stablecoin.",
      },
    ],
    news: [
      {
        date: "Feb 2026",
        headline: "Tether reports record $13B profit in 2025",
        summary: "Tether's 2025 annual attestation confirmed over $13 billion in profit, primarily from US Treasury holdings, cementing its position as one of the most profitable companies per employee.",
        tag: "Financials",
      },
      {
        date: "Jan 2026",
        headline: "Tether expands USDT to 5 new blockchains",
        summary: "Tether announced USDT support on Monad, Berachain, Sonic, Linea, and Scroll as part of its multi-chain strategy to maintain dominance.",
        tag: "Expansion",
      },
      {
        date: "Dec 2025",
        headline: "US lawmakers scrutinize Tether's reserves",
        summary: "A bipartisan group of US senators sent Tether a letter requesting detailed documentation of reserve composition ahead of potential stablecoin legislation.",
        tag: "Regulation",
      },
    ],
  },

  {
    id: "circle",
    name: "Circle",
    shortName: "USDC",
    logoText: "©",
    color: "#2775CA",
    type: "Centralized / Fiat-backed",
    founded: "2013",
    headquarters: "Boston, MA, USA",
    regulatoryStatus: "US-regulated, money transmitter licenses",
    marketCap: "$57B",
    marketShare: 25.3,
    website: "https://circle.com",
    description:
      "Circle Internet Financial is the issuer of USD Coin (USDC), the second-largest stablecoin and the largest regulated stablecoin. USDC is fully backed by cash and short-duration US Treasuries held in segregated accounts. Circle filed for an IPO in early 2024.",
    tags: ["Fiat-backed", "USD-pegged", "Regulated", "IPO 2024"],
    stablecoins: [
      {
        ticker: "USDC",
        name: "USD Coin",
        peg: "USD",
        status: "active",
        marketCap: "$57B",
        backing: "Cash & short-duration US Treasuries",
        chains: ["Ethereum", "Solana", "Arbitrum", "Base", "Optimism", "Polygon", "Avalanche", "Stellar", "Algorand", "Hedera", "Noble (Cosmos)"],
        launched: "2018",
        notes: "The most widely used regulated stablecoin. Preferred by institutional and DeFi users due to regulatory clarity.",
      },
      {
        ticker: "EURC",
        name: "Euro Coin",
        peg: "EUR",
        status: "active",
        marketCap: "$420M",
        backing: "Cash & equivalents",
        chains: ["Ethereum", "Solana", "Avalanche", "Stellar", "Base"],
        launched: "2022",
        notes: "Circle's Euro-denominated stablecoin targeting European markets.",
      },
    ],
    news: [
      {
        date: "Mar 2026",
        headline: "Circle files updated S-1 for NYSE listing",
        summary: "Circle submitted an updated IPO filing targeting a $5B valuation as stablecoin regulation advances in Congress, aiming for a mid-2026 listing.",
        tag: "IPO",
      },
      {
        date: "Feb 2026",
        headline: "USDC crosses $60B market cap for first time",
        summary: "Driven by institutional adoption and base layer usage, USDC briefly crossed $60B in circulating supply, its highest level since the 2022 depegging event.",
        tag: "Milestone",
      },
      {
        date: "Jan 2026",
        headline: "Circle launches USDC on 3 new L2 networks",
        summary: "Circle added native USDC support on Ink (Kraken's L2), Unichain, and Soneium, expanding its reach in the growing Ethereum L2 ecosystem.",
        tag: "Expansion",
      },
    ],
  },

  {
    id: "makerdao",
    name: "Sky / MakerDAO",
    shortName: "USDS",
    logoText: "M",
    color: "#1AAB9B",
    type: "Decentralized / Crypto-backed",
    founded: "2014",
    headquarters: "Cayman Islands (Foundation)",
    regulatoryStatus: "Decentralized protocol",
    marketCap: "$9.2B",
    marketShare: 4.1,
    website: "https://sky.money",
    description:
      "MakerDAO, rebranded to Sky in 2024, is the creator of DAI — one of the first and largest decentralized stablecoins. DAI is generated by locking collateral (ETH, WBTC, RWA, and other assets) in Maker Vaults. The protocol rebranded to Sky and launched USDS as an upgraded successor to DAI.",
    tags: ["Decentralized", "USD-pegged", "Crypto-backed", "RWA"],
    stablecoins: [
      {
        ticker: "DAI",
        name: "Dai",
        peg: "USD",
        status: "active",
        marketCap: "$5.2B",
        backing: "Crypto collateral (ETH, WBTC, RWA)",
        chains: ["Ethereum", "Arbitrum", "Optimism", "Base", "Polygon", "Gnosis", "Avalanche"],
        launched: "2017",
        notes: "Pioneer decentralized stablecoin. Still widely used in DeFi despite ongoing migration to USDS.",
      },
      {
        ticker: "USDS",
        name: "Sky Dollar",
        peg: "USD",
        status: "active",
        marketCap: "$4.0B",
        backing: "Crypto collateral & RWA",
        chains: ["Ethereum", "Solana", "Base"],
        launched: "2024",
        notes: "Upgraded successor to DAI under the Sky rebrand. Features improved governance and Sky Token rewards.",
      },
    ],
    news: [
      {
        date: "Feb 2026",
        headline: "Sky protocol integrates $2B in Real World Assets",
        summary: "Sky DAO voted to expand RWA collateral to $2B including tokenized US Treasuries from Ondo Finance and BlackRock's BUIDL fund.",
        tag: "RWA",
      },
      {
        date: "Jan 2026",
        headline: "USDS launches on Solana via Wormhole bridge",
        summary: "Sky expanded USDS to Solana using Wormhole's NTT framework, aiming to capture DeFi liquidity on the high-throughput chain.",
        tag: "Expansion",
      },
    ],
  },

  {
    id: "ethena",
    name: "Ethena",
    shortName: "USDe",
    logoText: "E",
    color: "#9B59B6",
    type: "Decentralized / Synthetic",
    founded: "2023",
    headquarters: "Cayman Islands",
    regulatoryStatus: "Unregulated (DeFi protocol)",
    marketCap: "$5.8B",
    marketShare: 2.6,
    website: "https://ethena.fi",
    description:
      "Ethena is a DeFi protocol that issues USDe, a synthetic dollar backed by delta-hedged positions in crypto derivatives. USDe holders can stake for sUSDe to earn yield from funding rates. Ethena has become the fastest-growing stablecoin in history by market cap.",
    tags: ["Synthetic", "USD-pegged", "Yield-bearing", "DeFi"],
    stablecoins: [
      {
        ticker: "USDe",
        name: "Ethena USDe",
        peg: "USD",
        status: "active",
        marketCap: "$4.9B",
        backing: "Delta-hedged crypto derivatives (BTC, ETH, SOL, stETH)",
        chains: ["Ethereum", "Arbitrum", "Base", "Mantle", "BNB Chain"],
        launched: "2024",
        notes: "Fastest-growing stablecoin in history. Backed by crypto spot + short perp positions.",
      },
      {
        ticker: "sUSDe",
        name: "Staked USDe",
        peg: "USD (yield-bearing)",
        status: "active",
        marketCap: "$0.9B",
        backing: "USDe (staked)",
        chains: ["Ethereum", "Arbitrum"],
        launched: "2024",
        notes: "Yield-bearing version of USDe. APY fluctuates based on funding rates (historically 5–20%+).",
      },
      {
        ticker: "USDtb",
        name: "Ethena USDtb",
        peg: "USD",
        status: "active",
        marketCap: "$290M",
        backing: "BlackRock BUIDL (tokenized T-bills)",
        chains: ["Ethereum"],
        launched: "2025",
        notes: "Conservative stablecoin backed entirely by BlackRock's tokenized Treasury fund.",
      },
      {
        ticker: "iUSDe",
        name: "Institutional USDe",
        peg: "USD",
        status: "announced",
        marketCap: "—",
        backing: "USDe",
        chains: ["Ethereum"],
        launched: "Announced 2025",
        notes: "Yield-bearing stablecoin designed for institutional investors with KYC/AML compliance layer.",
      },
    ],
    news: [
      {
        date: "Mar 2026",
        headline: "Ethena USDe surpasses $6B in circulating supply",
        summary: "Driven by high perpetual funding rates and DeFi integrations, USDe supply reached a new all-time high, further cementing its position as the third-largest decentralized stablecoin.",
        tag: "Milestone",
      },
      {
        date: "Feb 2026",
        headline: "Ethena partners with major CEXs for iUSDe distribution",
        summary: "Ethena announced partnerships with Deribit, OKX, and Bybit to distribute iUSDe to institutional clients as a yield-bearing collateral asset.",
        tag: "Partnership",
      },
      {
        date: "Jan 2026",
        headline: "Ethena launches on TON blockchain",
        summary: "Ethena expanded USDe to the TON blockchain to target Telegram's 900M+ user base, partnering with TON Foundation for native integration.",
        tag: "Expansion",
      },
    ],
  },

  {
    id: "paypal",
    name: "PayPal",
    shortName: "PYUSD",
    logoText: "P",
    color: "#003087",
    type: "Centralized / Fiat-backed",
    founded: "1998",
    headquarters: "San Jose, CA, USA",
    regulatoryStatus: "US-regulated (via Paxos), NYDFS approved",
    marketCap: "$890M",
    marketShare: 0.4,
    website: "https://paypal.com/us/digital-wallet/manage-money/crypto/pyusd",
    description:
      "PayPal USD (PYUSD) is a US dollar-pegged stablecoin issued by Paxos Trust Company under PayPal's brand. It is fully backed by US dollar deposits, short-term Treasuries, and cash equivalents. PYUSD is integrated into PayPal and Venmo for payments.",
    tags: ["Fiat-backed", "USD-pegged", "Payments", "NYDFS"],
    stablecoins: [
      {
        ticker: "PYUSD",
        name: "PayPal USD",
        peg: "USD",
        status: "active",
        marketCap: "$890M",
        backing: "USD deposits, T-bills & cash equivalents",
        chains: ["Ethereum", "Solana"],
        launched: "2023",
        notes: "Integrated into PayPal and Venmo apps for 430M+ users. Issued and managed by Paxos.",
      },
    ],
    news: [
      {
        date: "Jan 2026",
        headline: "PayPal enables PYUSD for cross-border business payments",
        summary: "PayPal launched a B2B cross-border payment feature using PYUSD, targeting SMEs sending money internationally with near-instant settlement on Solana.",
        tag: "Product",
      },
      {
        date: "Nov 2025",
        headline: "PYUSD supply contracts 40% amid stablecoin competition",
        summary: "PYUSD supply fell from its $1.4B peak as competition from USDC, USDT and newer entrants increased. Analysts cite limited DeFi integrations as a key headwind.",
        tag: "Analysis",
      },
    ],
  },

  {
    id: "ripple",
    name: "Ripple",
    shortName: "RLUSD",
    logoText: "R",
    color: "#346AA9",
    type: "Centralized / Fiat-backed",
    founded: "2012",
    headquarters: "San Francisco, CA, USA",
    regulatoryStatus: "NYDFS approved, NY trust charter",
    marketCap: "$420M",
    marketShare: 0.19,
    website: "https://ripple.com/rlusd",
    description:
      "Ripple USD (RLUSD) is a US dollar-backed stablecoin issued by Ripple, designed for cross-border payments and enterprise use cases. It is approved by the New York Department of Financial Services (NYDFS) and backed 1:1 by USD deposits and government bonds.",
    tags: ["Fiat-backed", "USD-pegged", "Cross-border", "NYDFS"],
    stablecoins: [
      {
        ticker: "RLUSD",
        name: "Ripple USD",
        peg: "USD",
        status: "active",
        marketCap: "$420M",
        backing: "USD deposits & US government securities",
        chains: ["XRP Ledger", "Ethereum"],
        launched: "2024",
        notes: "Designed for RippleNet cross-border payments. NYDFS-approved with monthly reserve attestations.",
      },
    ],
    news: [
      {
        date: "Feb 2026",
        headline: "Ripple integrates RLUSD into 20+ payment corridors",
        summary: "Ripple expanded RLUSD-based payment corridors to 20 new countries including Brazil, India, and several Southeast Asian markets through its banking partners.",
        tag: "Expansion",
      },
      {
        date: "Dec 2025",
        headline: "RLUSD supply grows 400% since launch",
        summary: "RLUSD supply reached $400M+ just one year after NYDFS approval, driven by Ripple's extensive banking partnerships and growing XRP Ledger DeFi ecosystem.",
        tag: "Milestone",
      },
    ],
  },

  {
    id: "firstdigital",
    name: "First Digital",
    shortName: "FDUSD",
    logoText: "F",
    color: "#F0B90B",
    type: "Centralized / Fiat-backed",
    founded: "2022",
    headquarters: "Hong Kong",
    regulatoryStatus: "Hong Kong trust company",
    marketCap: "$2.4B",
    marketShare: 1.07,
    website: "https://firstdigitallabs.com",
    description:
      "First Digital USD (FDUSD) is a stablecoin issued by First Digital Trust Limited, a Hong Kong-regulated trust company. It gained rapid adoption as Binance's preferred stablecoin following the discontinuation of BUSD. FDUSD is primarily used on BNB Chain.",
    tags: ["Fiat-backed", "USD-pegged", "Asia", "Binance ecosystem"],
    stablecoins: [
      {
        ticker: "FDUSD",
        name: "First Digital USD",
        peg: "USD",
        status: "active",
        marketCap: "$2.4B",
        backing: "USD deposits & T-bills",
        chains: ["Ethereum", "BNB Chain", "Sui"],
        launched: "2023",
        notes: "Rose to prominence after BUSD was discontinued. Heavily used in Binance trading pairs.",
      },
    ],
    news: [
      {
        date: "Mar 2026",
        headline: "First Digital expands FDUSD to Sui and SeiV2",
        summary: "First Digital announced FDUSD support on Sui and Sei V2 blockchains, targeting Asian DeFi markets with high TPS requirements.",
        tag: "Expansion",
      },
      {
        date: "Jan 2026",
        headline: "Allegations against First Digital Trust investigated",
        summary: "Justin Sun's public allegations against FDT regarding fund mismanagement were investigated by Hong Kong authorities; FDT denied all claims and provided attestation documents.",
        tag: "Controversy",
      },
    ],
  },

  {
    id: "paxos",
    name: "Paxos",
    shortName: "USDP",
    logoText: "Px",
    color: "#00C2B2",
    type: "Centralized / Fiat-backed",
    founded: "2012",
    headquarters: "New York, USA",
    regulatoryStatus: "NYDFS regulated (trust company), Abu Dhabi regulated",
    marketCap: "$900M",
    marketShare: 0.4,
    website: "https://paxos.com",
    description:
      "Paxos Trust Company is a regulated blockchain infrastructure platform and stablecoin issuer. Paxos issues USDP and also provides white-label stablecoin infrastructure (powering PYUSD for PayPal). Paxos holds NYDFS trust charter and a regulatory license in Abu Dhabi.",
    tags: ["Fiat-backed", "USD-pegged", "Infrastructure", "NYDFS"],
    stablecoins: [
      {
        ticker: "USDP",
        name: "Pax Dollar",
        peg: "USD",
        status: "active",
        marketCap: "$130M",
        backing: "USD deposits & T-bills",
        chains: ["Ethereum", "BNB Chain"],
        launched: "2018",
        notes: "Originally called PAX. One of the first NYDFS-approved stablecoins.",
      },
      {
        ticker: "PAXG",
        name: "PAX Gold",
        peg: "XAU (Gold)",
        status: "active",
        marketCap: "$770M",
        backing: "Physical gold (LBMA-approved vaults)",
        chains: ["Ethereum"],
        launched: "2019",
        notes: "Tokenized gold backed by physical gold bars in Brink's vaults in London.",
      },
      {
        ticker: "PYUSD",
        name: "PayPal USD",
        peg: "USD",
        status: "active",
        marketCap: "$890M",
        backing: "USD deposits & T-bills",
        chains: ["Ethereum", "Solana"],
        launched: "2023",
        notes: "Issued by Paxos on behalf of PayPal under a white-label arrangement.",
      },
      {
        ticker: "USDG",
        name: "Global Dollar",
        peg: "USD",
        status: "active",
        marketCap: "$170M",
        backing: "USD deposits & T-bills",
        chains: ["Ethereum"],
        launched: "2024",
        notes: "Network stablecoin in partnership with DBS Bank, Robinhood, and others. Yield shared with partners.",
      },
      {
        ticker: "HKDG",
        name: "Global HKD",
        peg: "HKD",
        status: "announced",
        marketCap: "—",
        backing: "HKD deposits",
        chains: ["Ethereum"],
        launched: "Announced 2025",
        notes: "Hong Kong Dollar stablecoin planned under Paxos's ADGM (Abu Dhabi) regulatory license.",
      },
    ],
    news: [
      {
        date: "Feb 2026",
        headline: "Paxos launches Global Dollar Network with DBS and Robinhood",
        summary: "Paxos expanded the Global Dollar (USDG) network to include DBS Bank, Robinhood, and Galaxy Digital, offering partners a share of reserve yield in exchange for distribution.",
        tag: "Partnership",
      },
      {
        date: "Dec 2025",
        headline: "Paxos receives Abu Dhabi FSRA license for global stablecoin ops",
        summary: "The Abu Dhabi Global Market's FSRA granted Paxos a full license to issue and manage stablecoins in ADGM, setting the stage for non-USD stablecoin products.",
        tag: "Regulation",
      },
    ],
  },

  {
    id: "frax",
    name: "Frax Finance",
    shortName: "FRAX",
    logoText: "Fx",
    color: "#EC4899",
    type: "Decentralized / Hybrid",
    founded: "2020",
    headquarters: "Decentralized",
    regulatoryStatus: "Unregulated (DeFi protocol)",
    marketCap: "$450M",
    marketShare: 0.2,
    website: "https://frax.finance",
    description:
      "Frax Finance is a pioneering decentralized stablecoin protocol that introduced a hybrid algorithmic-collateralized model. The protocol has evolved to offer multiple stablecoins and DeFi primitives including a decentralized lending market and a liquid ETH staking token.",
    tags: ["Hybrid", "USD-pegged", "DeFi", "Algorithmic"],
    stablecoins: [
      {
        ticker: "FRAX",
        name: "Frax",
        peg: "USD",
        status: "active",
        marketCap: "$270M",
        backing: "USDC + FXS (algorithmic)",
        chains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "Avalanche", "BNB Chain", "Fraxtal"],
        launched: "2020",
        notes: "Original partially-algorithmic stablecoin. Transitioning to fully-collateralized model.",
      },
      {
        ticker: "frxUSD",
        name: "Frax USD",
        peg: "USD",
        status: "active",
        marketCap: "$130M",
        backing: "BlackRock BUIDL + USDC",
        chains: ["Ethereum", "Fraxtal"],
        launched: "2024",
        notes: "Next-generation fully-backed Frax stablecoin backed by tokenized T-bills and USDC.",
      },
      {
        ticker: "sfrxUSD",
        name: "Staked Frax USD",
        peg: "USD (yield-bearing)",
        status: "active",
        marketCap: "$50M",
        backing: "frxUSD (staked)",
        chains: ["Ethereum"],
        launched: "2024",
        notes: "Yield-bearing version of frxUSD earning protocol revenues.",
      },
      {
        ticker: "FPI",
        name: "Frax Price Index",
        peg: "CPI basket",
        status: "active",
        marketCap: "$8M",
        backing: "FRAX + algorithmic",
        chains: ["Ethereum"],
        launched: "2022",
        notes: "Inflation-resistant stablecoin pegged to the US Consumer Price Index rather than USD.",
      },
    ],
    news: [
      {
        date: "Feb 2026",
        headline: "Frax v3 fully transitions to RWA-backed model",
        summary: "Frax Finance completed its transition to frxUSD as the primary stablecoin, backed by BlackRock's BUIDL and other tokenized Treasuries, abandoning partial algorithmic backing.",
        tag: "Protocol",
      },
      {
        date: "Jan 2026",
        headline: "Fraxtal L2 total value locked hits $500M",
        summary: "Frax's native Layer 2 blockchain Fraxtal reached $500M TVL, driven by DeFi protocols migrating to the Frax ecosystem for lower fees and native FRAX liquidity.",
        tag: "Ecosystem",
      },
    ],
  },
];

// ── News aggregated across all issuers ───────────────────────────────────────
const ALL_NEWS = [
  {
    date: "Mar 2026",
    headline: "US Senate passes landmark Stablecoin Act",
    summary: "The GENIUS Act (Guiding and Establishing National Innovation for US Stablecoins) passed the Senate 68-32, establishing the first federal framework for payment stablecoin issuers, requiring 1:1 backing and monthly audits.",
    tag: "Regulation",
    issuer: "Industry",
  },
  {
    date: "Mar 2026",
    headline: "Ethena USDe surpasses $6B in circulating supply",
    summary: "Driven by high perpetual funding rates and DeFi integrations, USDe supply reached a new all-time high.",
    tag: "Milestone",
    issuer: "Ethena",
  },
  {
    date: "Mar 2026",
    headline: "Circle files updated S-1 for NYSE listing",
    summary: "Circle submitted an updated IPO filing targeting a $5B valuation as stablecoin regulation advances in Congress.",
    tag: "IPO",
    issuer: "Circle",
  },
  {
    date: "Feb 2026",
    headline: "Tether reports record $13B profit in 2025",
    summary: "Tether's 2025 annual attestation confirmed over $13 billion in profit, primarily from US Treasury holdings.",
    tag: "Financials",
    issuer: "Tether",
  },
  {
    date: "Feb 2026",
    headline: "Sky protocol integrates $2B in Real World Assets",
    summary: "Sky DAO voted to expand RWA collateral to $2B including tokenized US Treasuries from Ondo Finance and BlackRock's BUIDL fund.",
    tag: "RWA",
    issuer: "Sky / MakerDAO",
  },
  {
    date: "Feb 2026",
    headline: "Paxos launches Global Dollar Network with DBS and Robinhood",
    summary: "Paxos expanded the Global Dollar (USDG) network to include DBS Bank, Robinhood, and Galaxy Digital.",
    tag: "Partnership",
    issuer: "Paxos",
  },
  {
    date: "Feb 2026",
    headline: "Ripple integrates RLUSD into 20+ payment corridors",
    summary: "Ripple expanded RLUSD-based payment corridors to 20 new countries including Brazil, India, and Southeast Asia.",
    tag: "Expansion",
    issuer: "Ripple",
  },
  {
    date: "Jan 2026",
    headline: "PayPal enables PYUSD for cross-border business payments",
    summary: "PayPal launched a B2B cross-border payment feature using PYUSD, targeting SMEs with near-instant Solana settlement.",
    tag: "Product",
    issuer: "PayPal",
  },
  {
    date: "Jan 2026",
    headline: "USDC crosses $60B market cap for first time",
    summary: "Driven by institutional adoption and base layer usage, USDC briefly crossed $60B in circulating supply.",
    tag: "Milestone",
    issuer: "Circle",
  },
  {
    date: "Dec 2025",
    headline: "Stablecoin market cap hits $225B all-time high",
    summary: "The total stablecoin market capitalization reached $225B in December 2025, surpassing the previous all-time high of $180B set in 2022.",
    tag: "Market",
    issuer: "Industry",
  },
];
